### ISSUE TITLE
would be good to mark `Version 2.2.0Beta1` as pre-release

### ISSUE THREAD

**Issue by chenrui333** [orbcode/orbuculum#155]
👋 since `Version 2.2.0Beta1` is a beta release, it might be better to mark it as pre-release. Thanks!

https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository

**Comment by mubes** [comment]
Hi Rui,

Under normal conditions I'd agree, but without this build ORBTrace 1.4.0
simply doesn't work, so I needed it to have a bit of a higher profile :-)
tbh I'm sure it will be fine for most users, but the osx and windows
testing is thin simply because I don't use those...that's where I expect
any problems to be.

Dave
