### ISSUE TITLE
Develop branch doesn't build with WITH_FPGA=0

### ISSUE THREAD

**Issue by karlp** [orbcode/orbuculum#32]
You guys really need a travis or something build that tries building various modes for you :)

in orbuculum.c:1099 we have
```
   /* Start the filewriter */
    IF_WITH_FIFOS( fifoFilewriter( _r.f, options.filewriter, options.fwbasedir ) );
```
and it would _seem_ that options.fwbasedir is "file writer base dir" ?  or at least, that'swhat the fifoFilewriter method expects.

However, in the options struct at line 136:
```
    /* FPGA Information */
    IF_INCLUDE_FPGA_SUPPORT( char *fwbasedir );          /* Where the firmware is stored */
```
Which seems to be something else?  

It's not actually _used_ anywhere though, it's never set either, not by any of the command line options.   Given these amgiuities,  I can make it _compile_ by just 
```diff
diff --git a/Src/orbuculum.c b/Src/orbuculum.c
index 785bb39..012e32b 100644
--- a/Src/orbuculum.c
+++ b/Src/orbuculum.c
@@ -1096,7 +1096,7 @@ int main( int argc, char *argv[] )
 #endif
 
     /* Start the filewriter */
-    IF_WITH_FIFOS( fifoFilewriter( _r.f, options.filewriter, options.fwbasedir ) );
+    IF_WITH_FIFOS( fifoFilewriter( _r.f, options.filewriter, NULL ) );
 
 #ifdef INCLUDE_FPGA_SUPPORT
 

```

But I don't know what the "real" fix is I'm sorry.

**Comment by mubes** [comment]
the `fwbasedir` was originally used for dynamically loading the fpga from the app which is why it was conditioned on FPGA_SUPPORT, but it got re-purposed for the filewriter (which is generally not used) at some point so became inconsistent. I've cleared everything up and made the requirement for a path explicit in the `-w` call for the filewriter.

...but you are right, travis would have picked this up, and thanks for sorting that issue.
