### ISSUE TITLE
Feature request: Command line option to switch colour palettes

### ISSUE THREAD

**Issue by Syncena** [orbcode/orbuculum#47]
The default colour palette for the Orb tools is not ideal when used with a pale window background; the light colours (e.g. yellow, cyan, green) are more or less illegible:

![Screenshot 2020-12-20 at 15 26 12](https://user-images.githubusercontent.com/38246447/102717067-d1c9d780-42d7-11eb-87b9-e721f4f78282.png)

There's a compile-time option to switch off colourisation, but it would be nice to have a command line option to select from some built-in palettes.

**Comment by mubes** [comment]
This is fixed in https://github.com/orbcode/orbuculum/commit/ffd1505a715a6197303c618869d3609ecca44f8f by means of creating a number of uicolours_xxx.h files in the Inc directory. You can then select which of these you want to build with via defines at the head of the makefile. Please hack up your own preference and send it in. Once we've got a few, I'll recode them into an array so they can be selected from the command line...but it needs people to submit a few that they like, you really don't want me doing look-and-feel stuff, it won't end well.

DAVE
